build.zig
src/Coff/Options.zig
src/Elf/Options.zig
src/MachO.zig
src/MachO/Archive.zig
src/MachO/Atom.zig
src/MachO/CodeSignature.zig
src/MachO/Dylib.zig
src/MachO/Object.zig
src/MachO/Options.zig
src/MachO/dead_strip.zig
src/MachO/fat.zig
src/Zld.zig
src/main.zig
src/mm.zig

Still more to do, but here's an example improvement of linking `redis-server` with standalone `zld` vs Apple's `ld64` (no `-dead_strip` though!):

macho: improve linking speed, reduce memory usage

---

src/Elf.zig
src/Elf/Archive.zig
src/Elf/Atom.zig
src/Elf/Object.zig
src/Elf/Options.zig
src/Elf/gc.zig
src/MachO/dead_strip.zig
src/test.zig

In summary, reduce number of redundant LOCs making the codebase more manageable, reduce memory allocs for parsed objects/archives, improve GC mechanism and move to separate module `Elf/gc.zig`, simplify inserting new sections from input files (uses section precedence and always keeps sections pre-sorted).
TODO when GCing atoms, if a section header should cease to exist, it is currently not removed from the output file.

elf: simplify like macho linker

---

build.zig
src/MachO.zig
src/MachO/Atom.zig
src/MachO/DwarfInfo.zig
src/MachO/Object.zig
src/MachO/dead_strip.zig
src/Zld.zig
src/tracy.zig

Prior to the regression, we would unnecessarily spin in `markLive` routine when dead stripping due to inability to handle target atoms described by a hard-coded in-section address (combination of `r_extern == 0` and `r_pcrel == 0` which normally occurs in `X86_64_RELOC_UNSIGNED`). This is now fixed by caching sorted source symbols by address per object and finding the containing atom of this type of relocation, and marking it live.
**EDIT:** I messed up the initial patch as I didn't take into account `r_extern == 0` and `r_pcrel == 1` which normally occurs in `X86_64_RELOC_SIGNED`, and then I made a very difficult to debug typo in the new code, but finally we are here. I've therefore updates the measurements below.
The link time of `stage3` with dead stripping has now been reduced by 1 …

Add Tracy integration and fix performance regression in MachO x86_64

---

src/MachO.zig
src/MachO/Atom.zig
src/MachO/DwarfInfo.zig
src/MachO/dead_strip.zig

They are implicitly marked as live.

macho: skip atomless synthetic globals in dead_strip

---

src/Wasm.zig
src/Wasm/Archive.zig
src/Wasm/Atom.zig
src/Wasm/Object.zig
src/Wasm/emit_wasm.zig

- export data symbols as global
- Fix archive table of symbols parsing
- Fix type index relocations
- Fix relocations for atoms with aliases

Various wasm-linker improvements

---

.github/workflows/main.yml

The current dependencies are using node12, which is deprecated and will no longer be supported from summer 2023. The new versions are using node16 instead.

bump CI dependency versions

---

src/Wasm.zig
src/Wasm/Object.zig
src/Wasm/Options.zig
src/Wasm/Symbol.zig
src/Wasm/emit_wasm.zig
src/Wasm/sections.zig

Implements several fixes to allow the linker to successfully link Zig's behavior test suite with libc and compiler_rt.
- fix index to global for exported data symbols
- fully support indirect function table
- emit the correct import name
- improve function pointer support
- Implement `--strip` flag
- fix table limits

misc fixes

---

src/Wasm.zig
src/Wasm/Options.zig
src/Wasm/Symbol.zig

--export=<value> allows the user to provide one or multiple symbols
to forcefully export to the host environment. When a symbol is not
resolved (found), it produces a linker error.
--export-dynamic will export any non-hidden global symbol.

support --export and --export-dynamic

---

src/Wasm.zig
src/Wasm/Atom.zig

We now have a consistent way to obtain the virtual address of a data symbol. This virtual address is used for both exporting data symbols and for relocations.

wasm: export data using correct virtual address

---

src/Wasm.zig
src/Wasm/Atom.zig
src/Wasm/Object.zig
src/Wasm/Options.zig
src/Wasm/emit_wasm.zig
src/main.zig

This implements the `__heap_base` symbol which is referenced by libc's allocator/brk and requires it to fulfill its allocations. In addition, this implements some fixes in `setupInitFuncs` and also implements the `--import-symbols` flag. This means zld can now successfully link with WASI-libc!

Support linking with WASI-libc

---

build.zig
src/Elf.zig
src/Elf/Object.zig
src/MachO.zig
src/MachO/Dylib.zig
src/MachO/Object.zig
src/MachO/UnwindInfo.zig
src/MachO/dead_strip.zig
src/MachO/dyld_info/Rebase.zig
src/MachO/dyld_info/bind.zig
src/MachO/eh_frame.zig
src/MachO/thunks.zig
src/Wasm.zig
src/Wasm/Object.zig
src/Wasm/emit_wasm.zig
src/Wasm/sections.zig
src/tapi.zig
src/tapi/yaml.zig
src/test.zig
test/test.zig

Updates to the new build API as well as the new for-loop syntax. Syntax changes have been performed by running 'zig fmt'.
The build changes no longer support depending on the same file within more than 1 module. To prevent having to fully restructure the test suite, we set the main_pkg_path to the root directory to allow for imports outside the 'src' directory.
closes #34

update to latest master build of Zig

---

src/Elf.zig
src/Elf/Archive.zig
src/Elf/Object.zig
src/Elf/Options.zig
src/test.zig

This enables `ld.zld` to be used as a cross-linker for ELF files.

elf: auto-infer target CPU architecture

---

src/Wasm.zig
src/Wasm/Atom.zig
src/Wasm/Object.zig
src/Wasm/Options.zig
src/Wasm/types.zig

This implements TLS relocations and fixes various issues in the shared-memory implementation. With these additions, we can now correctly link the threading example from the Zig main repo. The last remaining step for full static-linking support is garbage collection.

wasm: Finish TLS & shared-memory implementation

---

src/Wasm.zig
src/Wasm/Atom.zig
src/Wasm/Object.zig
src/Wasm/Symbol.zig
src/Wasm/emit_wasm.zig

Implements garbage collection to remove unreferenced symbols and their sections. Also fixes a TLS bug and improves the performance by 66% (3sec to 1sec in debug) due to a logical bug in `parseIntoAtoms`. (This is while linking Zig's behavior test suite for Wasm with compiler_rt and libc).

wasm - implement garbage collection

---

.github/workflows/main.yml
build.zig
src/MachO/Object.zig
test/macho.zig
test/test.zig

This is in particular very important to the Zig language which allows exporting the same symbol under different names. For instance, it is possible to have a case such that:
```
...
4258 T _foo
4258 T _bar
...
```
In this case we need to keep track of both symbol names when resolving FDEs and unwind records.
Also add ability to shell out to Zig when running tests - we can now build objects using Zig toolchain also!

macho: tie FDEs and unwind records to all symbol aliases

---

src/Wasm.zig
src/Wasm/Atom.zig
src/Wasm/Object.zig
src/Wasm/emit_wasm.zig

Improves the algorithms in `parseIntoAtoms` to improve the performance of the linker. Also first writes to a buffer before writing the final binary to the file, reducing the amount of syscalls and slightly improving the runtime performance as well.

wasm: improve linker performance

---

src/Wasm.zig
src/Wasm/Atom.zig
src/Wasm/Object.zig

Rather than always parsing the entire object files into atoms, we now only parse alive symbols into atoms. This means we have to parse fewer atoms in general and increase the linking speed by ~10-20%.

wasm: parse atoms lazily

---

src/MachO.zig
src/MachO/Atom.zig
src/MachO/CodeSignature.zig
src/MachO/InternalObject.zig
src/MachO/Object.zig
src/MachO/Options.zig
src/MachO/Relocation.zig
src/MachO/eh_frame.zig
src/MachO/synthetic.zig
test/macho.zig

Thunks support is still missing though - coming up next!

macho: pass all non-x86_64 tests on aarch64

---

build.zig
build.zig.zon
src/MachO.zig
src/MachO/Atom.zig
src/MachO/Object.zig
src/MachO/Options.zig
src/MachO/Symbol.zig
src/MachO/UnwindInfo.zig
src/MachO/eh_frame.zig
src/MachO/load_commands.zig
src/MachO/relocatable.zig
src/main.zig
test/elf.zig
test/macho.zig
test/test.zig

macho: implement -r mode

---

build.zig
src/MachO.zig
src/MachO/Archive.zig
src/MachO/Atom.zig
src/MachO/DwarfInfo.zig
src/MachO/Dylib.zig
src/MachO/InternalObject.zig
src/MachO/Object.zig
src/MachO/Symbol.zig
src/MachO/relocatable.zig
src/main.zig
src/tracy.zig

Memory reduced to 1444.9MB from 2757.87MB according to Tracy.
Linker performance virtually unchanged:
```
$ hyperfine ./zld ./zld_old
Benchmark 1: ./zld
Time (mean ± σ):      4.351 s ±  0.027 s    [User: 3.547 s, System: 2.467 s]
Range (min … max):    4.308 s …  4.401 s    10 runs
Benchmark 2: ./zld_old
Time (mean ± σ):      4.345 s ±  0.020 s    [User: 3.844 s, System: 2.106 s]
Range (min … max):    4.319 s …  4.381 s    10 runs
Summary
./zld_old ran
1.00 ± 0.01 times faster than ./zld
```

macho: reduce heap allocations

---

src/MachO.zig
src/MachO/Archive.zig
src/MachO/Atom.zig
src/MachO/Object.zig
src/MachO/file.zig

This means we hand out indexes into this array to object files thereby allowing a single file descriptor per archive rather than be required to clone it per each object file that resides within.
This is an alternative to #107 which resolves upstream issue ziglang/zig#18827 while preserving the performance status quo.
EDIT: supersedes #107

macho: store open file descriptors globally

---

src/MachO/Object.zig

In `ld -r` mode, the linker will emit `N_GSYM` for any defined external symbols as well as private externals. In the former case, the thing is easy since `N_EXT` bit will be set in the nlist's type. In the latter however we will encounter a local symbol with `N_PEXT` bit set (non-extern, but was private external) which we also need to include when resolving symbol stabs.
The major change in the logic for parsing symbol stabs per input object file is that we no longer try to force-resolve a `N_GSYM` as a global symbol. This was a mistake since every symbol stab always describes a symbol defined within the parsed input object file. We then work out if we should forward `N_GSYM` in the output symtab after we have resolved all symbols, but never before - intel we lack when initially parsing …

macho: correctly find N_GSYM symbols when parsing symbol stabs

---

.github/workflows/main.yml
build.zig
src/MachO.zig
src/MachO/Atom.zig
src/MachO/Dylib.zig
src/MachO/InternalObject.zig
src/MachO/Object.zig
src/MachO/Options.zig
src/MachO/Relocation.zig
src/MachO/Symbol.zig
src/MachO/UnwindInfo.zig
src/MachO/dead_strip.zig
src/MachO/dyld_info/Trie.zig
src/MachO/dyld_info/bind.zig
src/MachO/eh_frame.zig
src/MachO/file.zig
src/MachO/hasher.zig
src/MachO/relocatable.zig
src/MachO/thunks.zig
src/main.zig

At the time of writing, comparison in linking #138 (`./new` is zld after rewrite, `./old` is current master, `./ld` is Apple's new linker, `./ld_classic` is Apple's old linker, and `./lld` is LLVM's stock linker):
Also, just for completeness, speed up in `-r` relocatable mode between old and new zld:

macho: speed up the linker by embracing multi-threaded approach

---

src/MachO.zig
src/MachO/Atom.zig
src/MachO/InternalObject.zig

Special symbols include explictly force undefined symbols passed via -u flag, missing entry point symbol, missing 'dyld_stub_binder' symbol, or missing '_objc_msgsend' symbol.

macho: report special symbols if undefined

---

src/MachO.zig
src/MachO/Options.zig
test/macho.zig

When clang is invoked with two `-arch` flags, it will pass `-arch_multiple` and `-final_output` to the linker. According to [LLD implementation](https://reviews.llvm.org/D105450), `-arch_multiple` is only used to signal to the linker that it should suffix undefined symbols errors/warnings with current architecture.

macho: handle -arch_multiple flag

---

src/MachO.zig
src/MachO/Options.zig
src/MachO/load_commands.zig
test/macho.zig

According to [lld](https://reviews.llvm.org/D105449), when clang is invoked with two -arch flags, it will:
1. call the linker driver twice, once for each arch
2. call `lipo` tool to merge two outputs into a single file `emit.sub_path` is the name of the temporary file the linker writes to. `final_output` is the name of the file lipo writes to after the link.

macho: handle -final_output arg

---

flake.lock
flake.nix

When using Nix for development, `zacho` will be fetched, built and installed automatically now. For context, `zacho` is `otool` on steroids written in Zig.

Add zacho via nix flake

---

src/Atom.zig
src/Dylib.zig
src/InternalObject.zig
src/MachO.zig
src/Object.zig
src/Relocation.zig
src/Symbol.zig
src/Thunk.zig
src/UnwindInfo.zig
src/dead_strip.zig
src/dyld_info/Rebase.zig
src/dyld_info/Trie.zig
src/dyld_info/bind.zig
src/eh_frame.zig
src/file.zig
src/relocatable.zig
src/synthetic.zig

This finishes migration of remaining indexes to safe indexes with the exception of `File` which will be done in a follow-up.
As an interesting observation, I believe that thanks to the rewrite of indexes, `bold` got a tiny bit faster, dropping below 1s when linking Zig's stage3 compiler (I have used an old setup for Zig so your mileage may vary when tested against up-to-date Zig repo!). Anyhow, the results:
Note that now we've got only Apple rewritten `ld` to beat!

Migrate remaining unsafe indexes to safe indexes except File
